### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by vaidaarman** [Team-PiRoutes/pet-costumes#19]
As a logged-in user, I want to be able to log out, so that someone else can't just come along and use my account

- [ ]  User's session should be cleared

- [ ]  User's cart should be cleared

- [ ]  redirect to show successful logout. </LoggedOut>

- [ ] User should no longer be able to access any features of being logged in, such as order history.

**Comment by AuroraVaughn** [comment]
Currently, we clear the cart with 
localStorage.removeItem("cartId")
localStorage.removeItem("cartId")
